cookie:
  name: session
  domain: localhost
  path: /
  sameSite: None
  expiry: 86400

management:
  endpoints:
    web:
      base-path: /monitor
      exposure:
        include: metrics
  server:
    port: 9000
